os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
"".print STEXT size=133 args=0x10 locals=0x58
	0x0000 00000 (interface_test1.go:13)	TEXT	"".print(SB), ABIInternal, $88-16
	0x0000 00000 (interface_test1.go:13)	MOVQ	(TLS), CX
	0x0009 00009 (interface_test1.go:13)	CMPQ	SP, 16(CX)
	0x000d 00013 (interface_test1.go:13)	JLS	123
	0x000f 00015 (interface_test1.go:13)	SUBQ	$88, SP
	0x0013 00019 (interface_test1.go:13)	MOVQ	BP, 80(SP)
	0x0018 00024 (interface_test1.go:13)	LEAQ	80(SP), BP
	0x001d 00029 (interface_test1.go:13)	FUNCDATA	$0, gclocals·dcd203adb68ce058f2ecc435fed378a1(SB)
	0x001d 00029 (interface_test1.go:13)	FUNCDATA	$1, gclocals·b566bf517073933b5de3b38142d02a51(SB)
	0x001d 00029 (interface_test1.go:13)	FUNCDATA	$2, gclocals·bfec7e55b3f043d1941c093912808913(SB)
	0x001d 00029 (interface_test1.go:13)	FUNCDATA	$3, "".print.stkobj(SB)
	0x001d 00029 (interface_test1.go:14)	PCDATA	$0, $0
	0x001d 00029 (interface_test1.go:14)	PCDATA	$1, $1
	0x001d 00029 (interface_test1.go:14)	XORPS	X0, X0
	0x0020 00032 (interface_test1.go:14)	MOVUPS	X0, ""..autotmp_11+64(SP)
	0x0025 00037 (interface_test1.go:14)	MOVQ	"".x+96(SP), AX
	0x002a 00042 (interface_test1.go:14)	MOVQ	AX, ""..autotmp_11+64(SP)
	0x002f 00047 (interface_test1.go:14)	PCDATA	$0, $1
	0x002f 00047 (interface_test1.go:14)	PCDATA	$1, $2
	0x002f 00047 (interface_test1.go:14)	MOVQ	"".x+104(SP), AX
	0x0034 00052 (interface_test1.go:14)	PCDATA	$0, $0
	0x0034 00052 (interface_test1.go:14)	MOVQ	AX, ""..autotmp_11+72(SP)
	0x0039 00057 (<unknown line number>)	NOP
	0x0039 00057 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0039 00057 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0040 00064 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $2
	0x0040 00064 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x0047 00071 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0047 00071 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x004b 00075 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x004b 00075 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x0050 00080 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0050 00080 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $3
	0x0050 00080 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_11+64(SP), AX
	0x0055 00085 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x0055 00085 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x005a 00090 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x0063 00099 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x006c 00108 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x0071 00113 (<unknown line number>)	MOVQ	80(SP), BP
	0x0076 00118 (<unknown line number>)	ADDQ	$88, SP
	0x007a 00122 (<unknown line number>)	RET
	0x007b 00123 (<unknown line number>)	NOP
	0x007b 00123 (interface_test1.go:13)	PCDATA	$1, $-1
	0x007b 00123 (interface_test1.go:13)	PCDATA	$0, $-1
	0x007b 00123 (interface_test1.go:13)	CALL	runtime.morestack_noctxt(SB)
	0x0080 00128 (interface_test1.go:13)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 6c 48  eH..%....H;a.vlH
	0x0010 83 ec 58 48 89 6c 24 50 48 8d 6c 24 50 0f 57 c0  ..XH.l$PH.l$P.W.
	0x0020 0f 11 44 24 40 48 8b 44 24 60 48 89 44 24 40 48  ..D$@H.D$`H.D$@H
	0x0030 8b 44 24 68 48 89 44 24 48 48 8b 05 00 00 00 00  .D$hH.D$HH......
	0x0040 48 8d 0d 00 00 00 00 48 89 0c 24 48 89 44 24 08  H......H..$H.D$.
	0x0050 48 8d 44 24 40 48 89 44 24 10 48 c7 44 24 18 01  H.D$@H.D$.H.D$..
	0x0060 00 00 00 48 c7 44 24 20 01 00 00 00 e8 00 00 00  ...H.D$ ........
	0x0070 00 48 8b 6c 24 50 48 83 c4 58 c3 e8 00 00 00 00  .H.l$PH..X......
	0x0080 e9 7b ff ff ff                                   .{...
	rel 5+4 t=16 TLS+0
	rel 60+4 t=15 os.Stdout+0
	rel 67+4 t=15 go.itab.*os.File,io.Writer+0
	rel 109+4 t=8 fmt.Fprintln+0
	rel 124+4 t=8 runtime.morestack_noctxt+0
"".main STEXT size=137 args=0x0 locals=0x58
	0x0000 00000 (interface_test1.go:17)	TEXT	"".main(SB), ABIInternal, $88-0
	0x0000 00000 (interface_test1.go:17)	MOVQ	(TLS), CX
	0x0009 00009 (interface_test1.go:17)	CMPQ	SP, 16(CX)
	0x000d 00013 (interface_test1.go:17)	JLS	127
	0x000f 00015 (interface_test1.go:17)	SUBQ	$88, SP
	0x0013 00019 (interface_test1.go:17)	MOVQ	BP, 80(SP)
	0x0018 00024 (interface_test1.go:17)	LEAQ	80(SP), BP
	0x001d 00029 (interface_test1.go:17)	FUNCDATA	$0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x001d 00029 (interface_test1.go:17)	FUNCDATA	$1, gclocals·568470801006e5c0dc3947ea998fe279(SB)
	0x001d 00029 (interface_test1.go:17)	FUNCDATA	$2, gclocals·bfec7e55b3f043d1941c093912808913(SB)
	0x001d 00029 (interface_test1.go:17)	FUNCDATA	$3, "".main.stkobj(SB)
	0x001d 00029 (interface_test1.go:18)	PCDATA	$0, $0
	0x001d 00029 (interface_test1.go:18)	PCDATA	$1, $0
	0x001d 00029 (<unknown line number>)	NOP
	0x001d 00029 (interface_test1.go:18)	PCDATA	$1, $1
	0x001d 00029 (interface_test1.go:18)	XORPS	X0, X0
	0x0020 00032 (interface_test1.go:14)	MOVUPS	X0, ""..autotmp_12+64(SP)
	0x0025 00037 (interface_test1.go:14)	PCDATA	$0, $1
	0x0025 00037 (interface_test1.go:14)	LEAQ	type.string(SB), AX
	0x002c 00044 (interface_test1.go:14)	PCDATA	$0, $0
	0x002c 00044 (interface_test1.go:14)	MOVQ	AX, ""..autotmp_12+64(SP)
	0x0031 00049 (interface_test1.go:14)	PCDATA	$0, $1
	0x0031 00049 (interface_test1.go:14)	LEAQ	""..stmp_0(SB), AX
	0x0038 00056 (interface_test1.go:14)	PCDATA	$0, $0
	0x0038 00056 (interface_test1.go:14)	MOVQ	AX, ""..autotmp_12+72(SP)
	0x003d 00061 (<unknown line number>)	NOP
	0x003d 00061 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x003d 00061 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0044 00068 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $2
	0x0044 00068 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x004b 00075 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x004b 00075 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x004f 00079 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x004f 00079 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x0054 00084 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0054 00084 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $0
	0x0054 00084 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_12+64(SP), AX
	0x0059 00089 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x0059 00089 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x005e 00094 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x0067 00103 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x0070 00112 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x0075 00117 (<unknown line number>)	MOVQ	80(SP), BP
	0x007a 00122 (<unknown line number>)	ADDQ	$88, SP
	0x007e 00126 (<unknown line number>)	RET
	0x007f 00127 (<unknown line number>)	NOP
	0x007f 00127 (interface_test1.go:17)	PCDATA	$1, $-1
	0x007f 00127 (interface_test1.go:17)	PCDATA	$0, $-1
	0x007f 00127 (interface_test1.go:17)	CALL	runtime.morestack_noctxt(SB)
	0x0084 00132 (interface_test1.go:17)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 70 48  eH..%....H;a.vpH
	0x0010 83 ec 58 48 89 6c 24 50 48 8d 6c 24 50 0f 57 c0  ..XH.l$PH.l$P.W.
	0x0020 0f 11 44 24 40 48 8d 05 00 00 00 00 48 89 44 24  ..D$@H......H.D$
	0x0030 40 48 8d 05 00 00 00 00 48 89 44 24 48 48 8b 05  @H......H.D$HH..
	0x0040 00 00 00 00 48 8d 0d 00 00 00 00 48 89 0c 24 48  ....H......H..$H
	0x0050 89 44 24 08 48 8d 44 24 40 48 89 44 24 10 48 c7  .D$.H.D$@H.D$.H.
	0x0060 44 24 18 01 00 00 00 48 c7 44 24 20 01 00 00 00  D$.....H.D$ ....
	0x0070 e8 00 00 00 00 48 8b 6c 24 50 48 83 c4 58 c3 e8  .....H.l$PH..X..
	0x0080 00 00 00 00 e9 77 ff ff ff                       .....w...
	rel 5+4 t=16 TLS+0
	rel 40+4 t=15 type.string+0
	rel 52+4 t=15 ""..stmp_0+0
	rel 64+4 t=15 os.Stdout+0
	rel 71+4 t=15 go.itab.*os.File,io.Writer+0
	rel 113+4 t=8 fmt.Fprintln+0
	rel 128+4 t=8 runtime.morestack_noctxt+0
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 19+4 t=28 go.info.[]interface {}+0
	rel 27+4 t=28 go.info.int+0
	rel 37+4 t=28 go.info.error+0
go.info."".print$abstract SDWARFINFO dupok size=19
	0x0000 04 2e 70 72 69 6e 74 00 01 01 11 78 00 00 00 00  ..print....x....
	0x0010 00 00 00                                         ...
	rel 14+4 t=28 go.info.interface {}+0
go.loc.os.(*File).close SDWARFLOC dupok size=0
go.info.os.(*File).close SDWARFINFO dupok size=55
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 63 6c 6f 73  .os.(*File).clos
	0x0010 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  e...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 ec  ..........~r0...
	0x0030 01 00 00 00 00 00 00                             .......
	rel 18+8 t=1 os.(*File).close+0
	rel 26+8 t=1 os.(*File).close+26
	rel 36+4 t=29 gofile..<autogenerated>+0
	rel 49+4 t=28 go.info.error+0
go.range.os.(*File).close SDWARFRANGE dupok size=0
go.isstmt.os.(*File).close SDWARFMISC dupok size=0
	0x0000 04 05 01 10 02 05 00                             .......
go.loc."".print SDWARFLOC size=41
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 07 00 9c 93 08 91 08 93 08 00 00 00 00 00 00 00  ................
	0x0020 00 00 00 00 00 00 00 00 00                       .........
	rel 0+8 t=50 "".print+0
	rel 8+8 t=50 "".print+133
go.info."".print SDWARFINFO size=63
	0x0000 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 01 9c 13 00 00 00 00 00 00 00 00  ................
	0x0020 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 0e 00 00 00 00 00     ...............
	rel 1+4 t=28 go.info."".print$abstract+0
	rel 5+8 t=1 "".print+0
	rel 13+8 t=1 "".print+133
	rel 24+4 t=28 go.info."".print$abstract+10
	rel 28+4 t=28 go.loc."".print+0
	rel 33+4 t=28 go.info.fmt.Println$abstract+0
	rel 37+8 t=1 "".print+57
	rel 45+8 t=1 "".print+113
	rel 53+4 t=29 gofile../Users/louyuting/Desktop/go/study_golang/study/basic/interface/interface_test1.go+0
go.range."".print SDWARFRANGE size=0
go.isstmt."".print SDWARFMISC size=0
	0x0000 04 0f 04 0e 03 03 01 19 02 07 01 2c 02 05 01 0a  ...........,....
	0x0010 02 0a 00                                         ...
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 00 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 00 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 00 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
go.string."test" SRODATA dupok size=4
	0x0000 74 65 73 74                                      test
go.loc."".main SDWARFLOC size=0
go.info."".main SDWARFINFO size=99
	0x0000 03 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 12 00 00 00 12 00 00  ................
	0x0040 00 00 00 06 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 00 00 00 00 00 0e 00 00 00  ................
	0x0060 00 00 00                                         ...
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+137
	rel 27+4 t=29 gofile../Users/louyuting/Desktop/go/study_golang/study/basic/interface/interface_test1.go+0
	rel 33+4 t=28 go.info."".print$abstract+0
	rel 37+8 t=1 "".main+32
	rel 45+8 t=1 "".main+61
	rel 53+4 t=29 gofile../Users/louyuting/Desktop/go/study_golang/study/basic/interface/interface_test1.go+0
	rel 62+4 t=28 go.info."".print$abstract+10
	rel 68+4 t=28 go.info.fmt.Println$abstract+0
	rel 72+8 t=1 "".main+61
	rel 80+8 t=1 "".main+117
	rel 88+4 t=29 gofile../Users/louyuting/Desktop/go/study_golang/study/basic/interface/interface_test1.go+0
go.range."".main SDWARFRANGE size=0
go.isstmt."".main SDWARFMISC size=0
	0x0000 04 0f 04 0e 03 08 01 18 02 07 01 2c 02 05 01 0a  ...........,....
	0x0010 02 0a 00                                         ...
""..inittask SNOPTRDATA size=32
	0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
""..stmp_0 SRODATA size=16
	0x0000 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 go.string."test"+0
type..namedata.*main.ity- SRODATA dupok size=12
	0x0000 00 00 09 2a 6d 61 69 6e 2e 69 74 79              ...*main.ity
type.*"".ity SRODATA size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 b5 ff 11 0c 00 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*main.ity-+0
	rel 48+8 t=1 type."".ity+0
runtime.gcbits.03 SRODATA dupok size=1
	0x0000 03                                               .
type..namedata.ty- SRODATA dupok size=5
	0x0000 00 00 02 74 79                                   ...ty
type..namedata.da- SRODATA dupok size=5
	0x0000 00 00 02 64 61                                   ...da
type."".ity SRODATA size=144
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 a2 d5 68 fa 07 08 08 19 00 00 00 00 00 00 00 00  ..h.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 02 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00  ........@.......
	0x0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0080 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.algarray+96
	rel 32+8 t=1 runtime.gcbits.03+0
	rel 40+4 t=5 type..namedata.*main.ity-+0
	rel 44+4 t=5 type.*"".ity+0
	rel 48+8 t=1 type..importpath."".+0
	rel 56+8 t=1 type."".ity+96
	rel 80+4 t=5 type..importpath."".+0
	rel 96+8 t=1 type..namedata.ty-+0
	rel 104+8 t=1 type.unsafe.Pointer+0
	rel 120+8 t=1 type..namedata.da-+0
	rel 128+8 t=1 type.unsafe.Pointer+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
type..importpath.unsafe. SRODATA dupok size=9
	0x0000 00 00 06 75 6e 73 61 66 65                       ...unsafe
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
gclocals·dcd203adb68ce058f2ecc435fed378a1 SRODATA dupok size=12
	0x0000 04 00 00 00 02 00 00 00 02 02 00 00              ............
gclocals·b566bf517073933b5de3b38142d02a51 SRODATA dupok size=12
	0x0000 04 00 00 00 02 00 00 00 00 02 02 00              ............
gclocals·bfec7e55b3f043d1941c093912808913 SRODATA dupok size=11
	0x0000 03 00 00 00 02 00 00 00 00 01 03                 ...........
"".print.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·568470801006e5c0dc3947ea998fe279 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 00 02                    ..........
"".main.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
